version: "3.9"

services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
      - ./scripts/init.sh:/init.sh
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/init.sh"]
    networks:
      - pdf-genie-net


  qdrant-storage:
    container_name: qdrant-storage
    image: qdrant/qdrant
    volumes:
      - ./qdrant_storage:/qdrant/storage
    depends_on:
      - ollama
    networks:
      - pdf-genie-net

  backend:
    container_name: backend
    build:
      context: ./backend
    depends_on:
      - qdrant-storage
    networks:
      - pdf-genie-net

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - pdf-genie-net


volumes:
  ollama_data:

networks:
  pdf-genie-net:
    driver: bridge
