version: "3.9"

services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./scripts/init.sh:/init.sh
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/init.sh"]

  qdrant-storage:
    container_name: qdrant-storage
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./vector_db/qdrant_storage:/qdrant/storage

volumes:
  ollama_data: