version: "3.9"

services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
      - ./scripts/init.sh:/init.sh
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/init.sh"]
    networks:
      - pdf-genie-net


  qdrant-storage:
    container_name: qdrant-storage
    image: qdrant/qdrant
    volumes:
      - ./qdrant_storage:/qdrant/storage
    depends_on:
      - ollama
    networks:
      - pdf-genie-net

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - EMBED_MODEL=${EMBED_MODEL}
      - GEN_MODEL=${GEN_MODEL}
      - UPLOAD_DIR=${UPLOAD_DIR}
      - OLLAMA_URL=${OLLAMA_URL}
      - QDRANT_URL=${QDRANT_URL}
      - F_URL=${F_URL}
    ports:
      - "8000:8000"
    depends_on:
      - qdrant-storage
    networks:
      - pdf-genie-net

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "5173:80"

volumes:
  ollama_data:

networks:
  pdf-genie-net:
    driver: bridge
